apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: handsonazurehello-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: handsonazurehello-back
    spec:
      containers:
      - name: handsonazurehello-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: handsonazurehello-back
spec:
  ports:
  - port: 6379
  selector:
    app: handsonazurehello-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: handsonazurehello
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: handsonazurehello
    spec:
      containers:
      - name: handsonazurehello
        image: handsonazureregistry.azurecr.io/handsonazurehello:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "handsonazurehello-back"
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: handsonazurehello
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: handsonazurehello